logging:
  file: Bank/logs/application.log


tpd:
  peer1Port: 8083
  peer2Port: 8088


spring:
  application:
    name: bank1
  profiles: peer1
  datasource:
    url: jdbc:mysql://localhost:3306/sep_b?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: 2001jovana
 #   data: classpath:import1.sql
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files: classpath:import1.sql
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor

      #eureka:
#  instance:
#    hostname: bank2-peer1
#    appname: bank2
 # client:
 #   register-with-eureka: true
#  fetch-registry: false
 #   service-url:
      #defaultZone: http://eureka-peer2:${tpd.peer2Port}/eureka

  #     defaultZone: http://localhost:8760/eureka
#  server:
#    enable-self-preservation: false

server:
  port: ${tpd.peer1Port}
  ssl:
    key-store-type: JKS
    key-store: sepKeystore.jks
    key-store-password: sep
    key-alias: kp
    trust-store: truststore.jks
    trust-store-password: sep
    enabled-protocols: TLSv1.2
    client-auth: want

---

spring:
  application:
    name: bank2
  profiles: peer2
  datasource:
    url: jdbc:mysql://localhost:3306/sep_b2?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: 2001jovana
  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor


server:
  port: 8088
  ssl:
    key-store-type: JKS
    key-store: sepKeystore.jks
    key-store-password: sep
    key-alias: kp
    trust-store: truststore.jks
    trust-store-password: sep
    enabled-protocols: TLSv1.2
    client-auth: want

