logging:
  file: Bank/logs/application.log


tpd:
  peer1Port: 8083
  peer2Port: 8088


spring:
  application:
    name: bank1
  profiles: peer1
  datasource:
    url: jdbc:mysql://localhost:3306/sep_bank?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: 2001jovana
    jpa:
      hibernate:
        ddl-auto: create
      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
      show-sql: true
      properties:
        hibernate:
          hbm2ddl:
            import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor


eureka:
  instance:
    hostname: bank-peer1
    appname: bank1
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      #defaultZone: http://eureka-peer2:${tpd.peer2Port}/eureka
      defaultZone: http://localhost:8761/eureka
#  server:
#    enable-self-preservation: false

server:
  port: ${tpd.peer1Port}

---

spring:
  application:
    name: bank2
  profiles: peer2
  datasource:
    url: jdbc:mysql://localhost:3306/sep_bank2?useSSL=false&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: 2001jovana
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    properties:
      hibernate:
        hbm2ddl:
          import_files_sql_extractor: org.hibernate.tool.hbm2ddl.MultipleLinesSqlCommandExtractor


server:
  port: 8088
eureka:
  instance:
    hostname: bank-peer2
    appname: bank2
  client:
    register-with-eureka: true
    fetch-registry: false
    service-url:
      #defaultZone: http://eureka-peer1:${tpd.peer1Port}/eureka
      defaultZone: http://localhost:8761/eureka
#  server:
#    enable-self-preservation: false


#-----------------------DATABASE--------------------------------------
